#!/usr/bin/env bash
# verify-markers.sh — assert every shipped fork feature survived into a patch
# (and, optionally, into the built binary).
#
# WHY THIS EXISTS
# Cumulative patches are regenerated by hand (`git diff <base>..HEAD`). Twice a
# feature has vanished in that step and nobody noticed for weeks:
#   * 2026-07-09 — the ffs series published WITHOUT RSXTexture.cpp, silently
#     dropping the #11912 road-flicker fix (see README "Corrected 2026-07-09").
#   * 2026-08-05 — the 0.7.x consolidation dropped GTK_PROBE_11912, the TIU
#     transition probe that localized that same bug. Marker counts across
#     generations: 0.6.0=2, tguard-v6=2, ffs-v4=2, 0.7.5-cumulative=0, 0.8.3=0.
# Both were invisible because the build still compiled and ran fine — the
# feature was just gone. A grep is cheap; a lost instrument is not.
#
# USAGE
#   scripts/verify-markers.sh [patch-file] [binary-or-appimage]
#     patch-file  defaults to the newest patches/*-dev.patch
#     binary      optional; greps `strings` output for the runtime markers too
# Exit 0 = every required marker present. Exit 1 = something was dropped.
set -uo pipefail

PATCH="${1:-}"
BIN="${2:-}"
cd "$(dirname "$0")/.." || exit 1

if [ -z "$PATCH" ]; then
    PATCH=$(ls -t patches/*-dev.patch 2>/dev/null | head -1)
fi
[ -f "$PATCH" ] || { echo "FATAL: no patch file (got '$PATCH')"; exit 1; }

# Required markers: string, and the release that introduced it. Anything listed
# here must appear in EVERY later cumulative patch — these are the features the
# fork exists to ship. Add a line whenever a new gated feature lands.
MARKERS=(
    "GTK_REMAP0_ONE|0.6.0|#11912 road-flicker fix (force-ONE remap decode)"
    "GTK_PROBE_11912|0.6.0|TIU transition probe — the instrument that localized #11912"
    "rpcs3_audio_stat|0.6.0|cellAudio telemetry -> /dev/shm"
    "is_device_lost|0.6.1-tguard-v6|tguard device-loss latch"
    "GTK_FENCE_FORCE_SIGNAL|0.6.1-ffs-v1|fence force-signal drive-through"
    "GTK_RSX_WATCHDOG|0.6.1-ffs-v3|anti-lock stage 2 (RSX progress watchdog)"
    "GTK_FIFO_RESYNC|0.6.1-ffs-v4|anti-lock stage 3b (FIFO desync net)"
    "rpcs3_perf_stat|0.7.1|perf overlay mirror -> /dev/shm"
    "GTK_SEMA_PARK|0.7.2|NV406E semaphore futex park"
    "GTK_FLIP_RETIRE|0.7.4|anti-lock stage 4 (flip-status force-retire)"
    "GTK_AV_READAHEAD|0.7.4|access-violation readahead"
    "GTK Crash Recovery|0.7.5|player-facing rescue overlay text"
    "GTK Edition|0.7.2|build self-identification"
)

# Markers that must ALSO survive into the shipped binary (literal strings in the
# code). is_device_lost is a symbol, not a string, so it is patch-only.
BINARY_EXEMPT="is_device_lost"

# An explicitly declared baseline may waive the feature gate. The declaration
# lives IN the patch file (committed, visible, greppable) -- never in an env
# var or a flag, which is how a waiver would go silent. The gate is reduced to
# build self-identification, not removed: a binary that cannot say what it is
# does not ship. Loud by design -- a waived gate is not a passed gate.
WAIVER=$(grep -m1 '^GTK-Markers-Waiver:' "$PATCH" 2>/dev/null | cut -d: -f2- | sed 's/^ *//')
if [ -n "$WAIVER" ]; then
    echo "!! MARKERS WAIVED: $WAIVER"
    echo "!! gate reduced to 'GTK Edition' (build self-identification) only"
    MARKERS=( "GTK Edition|0.7.2|build self-identification" )
fi

fail=0
echo "== markers in $(basename "$PATCH") =="
for entry in "${MARKERS[@]}"; do
    IFS='|' read -r marker since desc <<< "$entry"
    n=$(grep -cF "$marker" "$PATCH" 2>/dev/null || true)
    if [ "${n:-0}" -gt 0 ]; then
        printf "  ok    %-24s (%s)\n" "$marker" "$n hits"
    else
        printf "  MISS  %-24s since %s — %s\n" "$marker" "$since" "$desc"
        fail=1
    fi
done

if [ -n "$BIN" ]; then
    [ -f "$BIN" ] || { echo "FATAL: binary '$BIN' not found"; exit 1; }
    # An AppImage's payload is compressed (dwarfs/squashfs), so `strings` on the
    # wrapper finds nothing and every marker would report a false MISS. Extract
    # the inner ELF first. Verified 2026-08-05: strings on the 0.8.3 AppImage
    # returns 0 hits for a marker that is definitely in the build.
    case "$BIN" in
        *.AppImage)
            tmpd=$(mktemp -d) || exit 1
            trap 'rm -rf "$tmpd"' EXIT
            if ( cd "$tmpd" && "$OLDPWD/$BIN" --appimage-extract usr/bin/rpcs3 >/dev/null 2>&1 \
                 || "$BIN" --appimage-extract usr/bin/rpcs3 >/dev/null 2>&1 ); then
                inner=$(find "$tmpd" -name rpcs3 -type f 2>/dev/null | head -1)
                [ -n "$inner" ] && BIN="$inner"
            fi
            case "$BIN" in
                *.AppImage)
                    echo "  WARN  could not extract the AppImage (needs FUSE or"
                    echo "        --appimage-extract support); skipping binary check."
                    BIN="" ;;
            esac
            ;;
    esac
fi
if [ -n "$BIN" ]; then
    echo "== markers in $(basename "$BIN") =="
    for entry in "${MARKERS[@]}"; do
        IFS='|' read -r marker since desc <<< "$entry"
        case "$marker" in $BINARY_EXEMPT) continue ;; esac
        # NB: no `grep -q` here. Under `set -o pipefail`, grep -q exits at the
        # first match, strings dies of SIGPIPE, and pipefail turns that into a
        # failed pipeline — every marker would report a false MISS. Count
        # instead so the producer always runs to completion.
        if [ "$(strings -a "$BIN" 2>/dev/null | grep -cF "$marker")" -gt 0 ]; then
            printf "  ok    %s\n" "$marker"
        else
            printf "  MISS  %-24s not in binary — built without it?\n" "$marker"
            fail=1
        fi
    done
fi

if [ "$fail" -eq 0 ]; then
    echo "PASS — every shipped feature is present."
else
    echo "FAIL — a feature was dropped. Do not publish this patch/build until"
    echo "       the marker is restored or deliberately removed from the list."
fi
exit "$fail"
